### ISSUE TITLE
Feature request: Add >{stats} to Archive::BagIt->verify_bag()

### ISSUE THREAD

**Issue by RussellMcOrmond** [rjeschmi/Archive-BagIt#8]
There is a feature in Archive::BagIt::Fast's verify_bag() to fill in {stats} such as $bagit->{stats}->{size} which isn't currently supported in Archive::BagIt . This is a request for someone to add the feature, and possibly for others including Robert to suggest ideal ways to implement.  I may be able to put some resources to this in the future, but not at the moment.

**Comment by rjeschmi** [comment]
What version are you running BTW?

**Comment by RussellMcOrmond** [comment]
We are still running the 0.045 version at Canadiana, but checked with the 0.053-TRIAL before asking if it had been added (or was planned to be removed from ::Fast).
